# Generated by Django 3.2.15 on 2022-10-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='involve',
            old_name='ek_gene',
            new_name='ek_gene_id',
        ),
    ]
