# Generated by Django 3.2.15 on 2022-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20221008_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='involvem',
            name='ek_gene_id',
        ),
        migrations.AddField(
            model_name='involvem',
            name='bta',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for bta'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='cap',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for cap'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='equ',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for equ'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='gal',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for gal'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='human_entrez_id',
            field=models.BigIntegerField(default=-1, verbose_name='human entrez for msigdb'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='ovi',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for ovi'),
        ),
        migrations.AddField(
            model_name='involvem',
            name='sus',
            field=models.CharField(max_length=50, null=True, verbose_name='ensembl gene id for sus'),
        ),
    ]
