# Generated by Django 3.2.15 on 2023-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20221014_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF_Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('TF', models.TextField()),
                ('Gene', models.TextField()),
            ],
        ),
    ]
